### PyTorch and Tensors

Developed by Facebook's AI Research (FAIR) Lab, PyTorch is an open source machine learning library based on the Torch library. It is used for applications such as computer vision, natural language processing etc.

A tensor is a container which can house data in N dimensions, along with its linear operations.

0D -> Scalar

1D -> Vector (array)

2D -> Matrix (array of arrays)

3+D -> Tensors of higher rank or dimensionality

In [15]:
import torch
import numpy as np

In [6]:
## Creating an empty tensor of a given shape
shape = (5, 3)
x = torch.empty(shape)

print(x)

tensor([[1.5605e+06, 4.5857e-41, 1.5605e+06],
        [4.5857e-41, 1.0041e-09, 3.0716e-41],
        [9.9599e-10, 3.0716e-41, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 1.7283e-04],
        [2.6590e+23, 4.2249e-05, 4.6243e-44]])


In [8]:
## Creating a tensor of random values of a given shape
x = torch.rand(shape)

print(x)

tensor([[0.5493, 0.9622, 0.1751],
        [0.5209, 0.9567, 0.3764],
        [0.8732, 0.4641, 0.6027],
        [0.3197, 0.8999, 0.2844],
        [0.7771, 0.4252, 0.0919]])


In [9]:
# Creating a tensor of zeros of a given shape
x = torch.zeros(shape)

print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
# Creating a tensor of ones of a given shape
x = torch.ones(shape)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
# Creating a tensor of random numbers of specified dtypes of a given shape
x = torch.rand(shape, dtype=torch.double)

print(x)

tensor([[0.8208, 0.0671, 0.8645],
        [0.0383, 0.7097, 0.7919],
        [0.3006, 0.0215, 0.7505],
        [0.7470, 0.5493, 0.1431],
        [0.1064, 0.9183, 0.8379]], dtype=torch.float64)


In [13]:
## Printing the size of a tensor
print(x.size()) ## Elements accessible with the [] operator

torch.Size([5, 3])


In [21]:
## Creating a tensor from a numpy array or a regular list
nums = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
x = torch.tensor(nums)

print(x)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [33]:
## Creating a numpy array from a tensor
numsNew = x.cpu().detach().numpy() ## Detaches from the GPU and converts to numpy array

print(numsNew)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


NOTE: A NumPy ndarray is the class and array() is the function call that creates an ndarray.

In [36]:
## Adding/subtracting two tensors
y = torch.tensor(numsNew)

z = x + y ## z = torch.add(x, y) has the same effect
z1 = x - y ## z = torch.sub(x, y) has the same effect
print(z)
print(z1)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [37]:
## Addition/subtraction in-place
y.add_(x) ## Every function in PyTorch with a trailing underscore will do an in-place operation
print(y)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])


In [40]:
## Multiplying/dividing two tensors
z = x * y ## Element-wise multiplication (dot product)
z1 = x / y ## Element-wise division
print(z)
print(z1)

tensor([[  2,   8,  18,  32],
        [ 50,  72,  98, 128],
        [162, 200, 242, 288]])
tensor([[0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000]])


In [42]:
## Slicing operations using the [] operator
print(x[:, 2]) ## All rows, 2th column (prints a row for some reason)
print(x[1, :]) ## 1th row, all columns

tensor([ 3,  7, 11])
tensor([5, 6, 7, 8])


In [46]:
## Reshaping
a = torch.rand([4, 4], dtype=torch.float32) ## 4 rows, 4 columns
print(a)
b = a.view(2, 8) ## 2 rows, 8 columns
print(b)
c = a.view(8, 2) ## 8 rows, 2 columns
print(c)
d = a.view(-1, 8) ## Automatically decide rows, 8 columns
print(d)
e = a.view([4, 2, 2]) ## 4 of 2 rows, 2 columns
print(e)

tensor([[0.4355, 0.7209, 0.8918, 0.4781],
        [0.0526, 0.3758, 0.9294, 0.2838],
        [0.6136, 0.9023, 0.4720, 0.5345],
        [0.7002, 0.1711, 0.1932, 0.7559]])
tensor([[0.4355, 0.7209, 0.8918, 0.4781, 0.0526, 0.3758, 0.9294, 0.2838],
        [0.6136, 0.9023, 0.4720, 0.5345, 0.7002, 0.1711, 0.1932, 0.7559]])
tensor([[0.4355, 0.7209],
        [0.8918, 0.4781],
        [0.0526, 0.3758],
        [0.9294, 0.2838],
        [0.6136, 0.9023],
        [0.4720, 0.5345],
        [0.7002, 0.1711],
        [0.1932, 0.7559]])
tensor([[0.4355, 0.7209, 0.8918, 0.4781, 0.0526, 0.3758, 0.9294, 0.2838],
        [0.6136, 0.9023, 0.4720, 0.5345, 0.7002, 0.1711, 0.1932, 0.7559]])
tensor([[[0.4355, 0.7209],
         [0.8918, 0.4781]],

        [[0.0526, 0.3758],
         [0.9294, 0.2838]],

        [[0.6136, 0.9023],
         [0.4720, 0.5345]],

        [[0.7002, 0.1711],
         [0.1932, 0.7559]]])


In [47]:
## Checking for GPU support

if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print("Device {}: {}".format(i, torch.cuda.get_device_name(i)))

Device 0: NVIDIA GeForce GTX 1050 Ti


In [52]:
## Setting device = GPU

if torch.cuda.is_available():
    device = torch.device("cuda")

In [53]:
x = x.to(device) ## Takes the tensor x to GPU
print(x)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], device='cuda:0')


In [55]:
## The following fails because the tensor is currently on the GPU and needs to be detached from the GPU and transferred to the CPU
cpuz = x.numpy()
print(cpuz)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [56]:
cpuz = x.cpu().detach().numpy()
print(cpuz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


That's about it for now.